spring:
  application:
    name: aicc
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# Database configuration
database:
  mysql:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  postgres:
    url: jdbc:postgresql://localhost:5432/mydatabase?ApplicationName=aicc
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
