spring:
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# Database configuration
database:
  mysql:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  cdr:
    url: jdbc:mysql://localhost:3306/cdr_db?createDatabaseIfNotExist=true
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: secret
  password: secret

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket-name: ${S3_BUCKET_NAME:dummy-bucket}
    credentials:
      access-key: ${S3_ACCESS_KEY:dummy-access-key}
      secret-key: ${S3_SECRET_KEY:dummy-secret-key}